### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by jpxd** [filisko/pdo-plus#11]
When using this library in PHP8, the following error occurs:

```
Declaration of Filisko\PDOplus\PDO::query($statement, $mode = Filisko\PDOplus\PDO::ATTR_DEFAULT_FETCH_MODE, $arg3 = null, array $ctorargs = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
```

This can easily be fixed by changing the signature to the new one, but probably breaks this library for PHP7.
I don't know wether the two implementations can coexist.

I think a new major version of pdo-plus which is compatible with PHP8 might be the best option. This way we don't break older projects which often only get minor and patch version updates.
PHP7.4 only has active support for 7 months left, so most new projects will be using PHP8 since it is the current stable version.

See this link for the official PHP version support: https://www.php.net/supported-versions.php

**Comment by filisko** [comment]
Thanks @jpxd for reaching out. I will setup the CI first with Github Actions to run the tests in multiple PHP versions and then I have a look to this!

**Comment by jpxd** [comment]
Hi, is there any update on this? :)

**Comment by filisko** [comment]
Thanks @jpxd !!, I created a new release 4.0.0 and will keep the 7.2, 7.3, 7.4 versions in branch 3.x.x and add patches if anything comes up.

I added a couple of changes more to adapt better to the new PHP 8.0 PDO class. Now master branch is for >= php8.0 only.

**Comment by jpxd** [comment]
Thanks for the fast reply and for the new release!
