### ISSUE TITLE
Execute() binding is too "aggressive"

### ISSUE THREAD

**Issue by woytam** [filisko/pdo-plus#4]
Log from function `execute` with prepared statement is too aggressive with trying to bind values.
Ex.
```
$pdo->prepare('SELECT * FROM `db0`.`table` WHERE user = ?');
$pdo->execute(['John']);
```
will be logged as
```
SELECT * FROM `dbJohn`.`table` WHERE id = ?
```
See `db0` changed to `dbJohn`. Problem is in [PDOStatement.php#L89](https://github.com/filisko/pdo-plus/blob/b726cb52971d7d68fd0ef638d63f63f788dc7b2a/src/PDOStatement.php#L89) where is missing control, if `$input_parameters` are array of values or array of named params. Array of values have numerical indexes from 0.

I will make PR inspired from [comment on PHP.net](https://www.php.net/manual/en/pdostatement.debugdumpparams.php#113400).

**Comment by filisko** [comment]
Thank you @woytam :+1:
December was a busy month
