### ISSUE TITLE
Library PDOStatement does not extend extension PDOStatement

### ISSUE THREAD

**Issue by patrickkusebauch** [filisko/pdo-plus#8]
Since `\Filisko\PDOplus\PDOStatement` does not extend `\PDOStatement` This library does not work anywhere where parameter types are enforced. This is not a problem with the `PDO` class that follows LSP.

**Comment by filisko** [comment]
Hi, thanks for opening the issue.

It is true that `\Filisko\PDOplus\PDOStatement` does not extend `\PDOStatement`, it acts more like a decorator.

Can you give an example or more details about the issue please?

**Comment by patrickkusebauch** [comment]
Sure. I decided to use some DBAL library. The reason is clear - I might prefer it's API or maybe I need it for some ORM or whatnot. It does not really matter. 

These types of DBAL libraries often take a PDO object as a dependency for DB connection in the constructor.

I decide to use this library instead of the default PHP `PDO` object because I want to use this library for the purposes of logging my DB communication.

It is very common for PHP 7+ ready libraries to use parameter typing. Therefore somewhere in the DBAL library is a code like this:

`public function __construct(
        \PDOStatement $selectStatement,
        \PDOStatement $countStatement,
        MessageFactory $messageFactory,
        int $batchSize,
        int $fromNumber,
        ?int $count,
        bool $forward
    )`

This parameter typing is understandable since these `PDOStatement`s were created with the `PDO` object passed earlier. At that point, your library breaks the code, since your `PDOStatement` does not extend PHP's default `PDOStatement`.

Is this sufficient, or do you need extensive code examples?

In the end, I had to rewrite a part of your library and include that code manually in my codebase. If you understand the reasoning and are happy to, I could create a PR with the rewrite.

**Comment by patrickkusebauch** [comment]
The whole reason I got into this issue was that I have a package that does not have it's own Tracy panel but uses PDO for DB connection. So this package was a prime candidate to use in combination so that I could log its activity in Tracy.
